Enhance update_clojurescript script

diff --git a/script/update_clojurescript b/script/update_clojurescript
--- a/script/update_clojurescript
+++ b/script/update_clojurescript
@@ -9,13 +9,29 @@
 set -e
 cd `dirname $0`/..
 
+if [ ! -z "`git status --porcelain`" ]; then
+    echo "Error: org-html-slides working directory is not clean."
+    echo "Commit or stash any uncommitted changes before"
+    echo "running this script."
+    exit 1
+fi
+
 cd lib/clojurescript
+if [ ! -z "`git status --porcelain`" ]; then
+    echo "Error: ClojureScript working directory is not clean."
+    echo "Commit or stash any uncommitted changes before"
+    echo "running this script."
+    exit 1
+fi
+
 git checkout -q master
+
 if git pull | grep 'Already up-to-date' > /dev/null; then
     echo "ClojureScript is already up-to-date."
     exit 0
 else
     cd ../..
     git add -f lib/clojurescript
-    echo "ClojureScript updated; ready to commit."
+    git commit -m "Update ClojureScript submodule from master."
+    echo "ClojureScript updated."
 fi
